# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.17.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Build, GAE deploy
      - uses: actions/checkout@v2
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.1
        with:
          # The version of the gcloud SDK to be installed.  Example: 275.0.0
          # The service account email which will be used for authentication.
          service_account_email: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          # The service account key which will be used for authentication.
          service_account_key: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          APIKEY: ${{ secrets.FIREBASE_APIKEY }}
          AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
          DATABASEURL: ${{ secrets.FIREBASE_DATABASEURL }}
          PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
          STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
          MESSAGINGSENDERID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
          APPID: ${{ secrets.FIREBASE_APPID }}
          MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
          GOOGLEMAPS_APIKEY: ${{ secrets.GOOGLEMAPS_APIKEY}}
          ALGOLIA_ID: ${{ ZI3A3BYLFT} }
          ALGOLIA_SEARCH_APIKEY: ${{dd660cd8b43da0cc68310ac6a365438b}}
          
      - name: GAE deploy
        run: gcloud app deploy app.yaml --projecet mcaexpf-2020
