# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [15.14.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Build, GAE deploy
      - uses: actions/checkout@v2
      - name: Setup gcloud environment
        uses: google-github-actions/setup-gcloud@master
        with:
           project_id: ${{ secrets.GCP_PROJECT_ID }}
           service_account_key: ${{ secrets.GCP_SA_KEY }}
           export_default_credentials: true
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
        run: |
          npm install
          npm run build
        env:
          FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASEURL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECTID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGINGSENDERID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APPID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENTID }}
          GOOGLEMAPS_APIKEY: ${{ secrets.GOOGLEMAPS_APIKEY　}}
          ALGOLIA_ID: ${{ secrets.ALGOLIA_ID　}}
          ALGOLIA_SEARCH_APIKEY: ${{ secrets.ALGOLIA_SEARCH_APIKEY }}
          
      - name: GAE deploy
        run: gcloud app deploy app.yaml --projecet mcaexpf-2020
